### ISSUE TITLE
Link back to Vaadin Testbench Tutorial is broken

### ISSUE THREAD

**Issue by mpittkin** [vaadin/testbench-tutorial#10]
I think the title pretty much sums it up, the link is to:
https://vaadin.com/docs/-/part/testbench/testbench-tutorial.html

But the correct address is:
https://vaadin.com/docs/v8/testbench/testbench-tutorial.html

**Comment by alvarezguille** [comment]
Thanks for reporting this, fixed readme in  bcc8729
